SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_BG_COLOR = "black"
SCREEN_TITLE = "Pong"

PADDLE_WIDTH = 5
PADDLE_LEN = 1
PADDLE_MOVE_DIST = 20
PADDLE_COLOR = "white"
R_PADDLE_START_POS = (350, 0)
L_PADDLE_START_POS = (-350, 0)

BALL_COLOR = "white"
BALL_START_X_MOVE = 10
BALL_START_Y_MOVE = 10
BALL_START_MOVE_SPEED = 0.1
BALL_SPEED_MULTIPLIER = (
    0.9  # less means faster (at 0.5, the speed essentially doubles every hit)
)

SCOREBOARD_COLOR = "white"
SCORE_FONT = ("Courier", 80, "normal")
SCORE_POS_L = (-100, 200)
SCORE_POS_R = (100, 200)
WINNING_SCORE = 10

Y_BOUNCE_LIMIT = 280
PADDLE_BOUNCE_X_LIMIT = 320
PADDLE_HIT_DISTANCE = 50
X_MISS_LIMIT = 380

DASH_COLOR = "white"
